name: fotgraf_mobile
description: "Sawrly - صورلي - v1.2.4 Grid Fix: Inga tomma ytor under ProfileMediaGrids (Offer/Photo/Video). shrinkWrap + NeverScrollPhysics + arabisk empty-state istallet for engelska."
publish_to: 'none'
version: 1.2.15+20

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.0
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
